/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ps.view.form;

/**
 *
 * @author Rusimovic
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmenuMain = new javax.swing.JMenuBar();
        jmenuProduct = new javax.swing.JMenu();
        jmiProductNew = new javax.swing.JMenuItem();
        jmiProductView = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main form");

        jmenuProduct.setText("Product");

        jmiProductNew.setText("New");
        jmiProductNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductNewActionPerformed(evt);
            }
        });
        jmenuProduct.add(jmiProductNew);

        jmiProductView.setText("View");
        jmiProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductViewActionPerformed(evt);
            }
        });
        jmenuProduct.add(jmiProductView);

        jmenuMain.add(jmenuProduct);

        jmenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jmiAboutSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutSoftwareActionPerformed(evt);
            }
        });
        jmenuAbout.add(jmiAboutSoftware);

        jmenuMain.add(jmenuAbout);

        setJMenuBar(jmenuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProductNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductNewActionPerformed
      
        new FrmNewProduct(this, true).setVisible(true);
    }//GEN-LAST:event_jmiProductNewActionPerformed

    private void jmiAboutSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutSoftwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAboutSoftwareActionPerformed

    private void jmiProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductViewActionPerformed
        new FrmViewProducts(this, true).setVisible(true);
    }//GEN-LAST:event_jmiProductViewActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuBar jmenuMain;
    private javax.swing.JMenu jmenuProduct;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiProductNew;
    private javax.swing.JMenuItem jmiProductView;
    // End of variables declaration//GEN-END:variables
}
